name: Deploy App to GitHub Pages

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read
  pages: write
  id-token: write
  
jobs:
  # BUILD
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
      # Node Setup and Build
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        id: node-setup
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: |
          npm ci
          npm run build --if-present

      - name: Upload Artifacts
        id: upload-artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: build/
  
  # Deploy
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to Github Pages
        id: deploy
        uses: actions/deploy-pages@v4